name = "app"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXT_PUBLIC_ADMIN_USER = "MiqueiasRocha"

[[d1_databases]]
binding = "APP_CONFIG_D1"
database_name = "app_config"
database_id = "3f8b3029-3715-4c7d-97f5-7451eda8fb5a"
